stages:
  download_videos:
    cmd: python src/download_videos_from_db.py params.yaml
    outs:
      - data/artie_videos
  download:
    cmd: python src/download.py params.yaml
    outs:
      - data/CK+
      - data/FER2013
  data_augmentation:
    cmd: python src/bilstm_data_augmentation.py params.yaml
    outs:
      - data/CK_Augmented/emotions.csv
    deps:
      - data/CK+
      - data/FER2013
  normalization:
    cmd: python src/normalization.py params.yaml
    deps:
      - data/CK_Augmented/emotions.csv
    outs:
      - data/normalization
  training:
    cmd: python src/training.py params.yaml
    deps:
      - data/normalization
    params:
      - training.batch_size
      - training.epochs
      - training.train_percentage
    outs:
      - model/fer.h5
      - model/fer.json
    metrics:
      - metrics/scores.json:
          cache: false
    plots:
      - metrics/plots.csv