stages:
  download:
    cmd: python src/download.py params.yaml
    outs:
      - data/CK+
      - data/FER2013
      - data/LirisChildren
  data_augmentation:
    cmd: python src/bilstm_data_augmentation.py params.yaml
    outs:
      - data/CK_Augmented/CK+_augmented
    deps:
      - data/CK+
      - data/FER2013
      - data/LirisChildren
  normalization:
    cmd: python src/normalization.py params.yaml
    deps:
      - data/CK_Augmented/CK+_augmented
    outs:
      - data/normalization
  training:
    cmd: python src/training.py params.yaml
    deps:
      - data/normalization
    params:
      - training.batch_size
      - training.epochs
      - training.train_percentage
    outs:
      - model/fer.json
    metrics:
      - metrics/scores.json:
          cache: true
    plots:
      - metrics/plots.csv
artifacts:
  emotional-model:
    path: model/fer.h5
    type: model
    desc: 'Facial Emotion Recognition model'
    labels:
      - classification
      - CNN
    meta:
      framework: keras