stages:
  download_videos:
    cmd: python src/download_videos_from_db.py params.yaml
    outs:
      - data/artie_videos
  download:
    cmd: python src/download.py params.yaml
    outs:
      - data/CK+.zip
  data_augmentation:
    cmd: python src/bilstm_preprocess.py params.yaml
    outs:
      - data/CK_Augmented/emotions.csv
    deps:
      - data/CK+.zip
  normalization:
    cmd: python src/normalization.py params.yaml
    deps:
      - data/CK_Augmented/emotions.csv