general:
  active_datasets:
    ck: true
    fer2013: true
    liris: true

artie_videos:
  db:
    host: coruscant.artie.rocks
    port: 27017
    name: artie
  download_path: data/artie_videos

download:
  bucket_name: artie-datasets
  bucket_region: eu-west-3
  files_to_download:
  - CK+.zip
  - FER2013.zip
  - LIRISChildren.zip
  local_destination_path: data

data_augmentation:
  dataset_ck_images_path: data/CK+
  dataset_ck_emotions_path: data/CK+_emotions
  dataset_ck_emotions_augmented_path: data/CK_Augmented
  dataset_ck_images_augmented_path: data/CK_Augmented/CK+_augmented
  dataset_liris_videos_path: data/LIRISChildren
  dataset_liris_images_augmented_path: data/LIRIS_Augmented

normalization:
  csv_path: data/normalization/emotions.csv
  fer_2013_path: data/FER2013
  normalization_path: data/normalization

training:
  emotion_csv_file: data/normalization/emotions.csv
  metrics_path: metrics
  model_path: model
  num_labels: 7
  batch_size: 64
  epochs: 2
  early_stopping_patience: 10
  train_percentage: 0.75
  show_summary: true
  structure_layers:
  - CONV2D
  - MAXPOOLING2D
  - CONV2D
  - AVGPOOLING2D
  - CONV2D
  - AVGPOOLING2D
  - FLATTEN
  - DENSE
  - DROPOUT
  - DENSE
  - DROPOUT
  - DENSE
  structure_values:
  - - 32
    - 42
    - 42
    - relu
    - same
  - - 21
    - 21
    - 2
    - 2
  - - 32
    - 21
    - 21
    - relu
    - same
  - - 10
    - 10
    - 2
    - 2
  - - 64
    - 10
    - 10
    - relu
    - same
  - - 5
    - 5
    - 2
    - 2
  - []
  - - 3072
    - relu
    - same
  - - 0.5
  - - 3072
    - relu
    - valid
  - - 0.5
  - - 7
    - softmax
