artie_videos:
  db:
    host: coruscant.artie.rocks
    port: 27017
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    name: artie
  download_path: data/artie_videos

data_augmentation:
  dataset_images_path: data/CK+
  dataset_emotions_path: data/CK+_emotions
  dataset_emotions_augmented_path: data/CK_Augmented
  dataset_images_augmented_path: data/CK_Augmented/CK+_augmented

normalization:
  normalization_path: data/CK_Augmented/normalization