artie_videos:
  db:
    host: coruscant.artie.rocks
    port: 27017
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    name: artie
  download_path: data/artie_videos

download:
  access_key: ${AWS_ACCESS_KEY_ID}
  secret_key: ${AWS_SECRET_ACCESS_KEY}
  bucket_name: artie-datasets
  bucket_region: eu-west-3
  files_to_download:
    - CK+.zip
    - FER2013.zip
  local_destination_path: data

data_augmentation:
  dataset_images_path: data/CK+
  dataset_emotions_path: data/CK+_emotions
  dataset_emotions_augmented_path: data/CK_Augmented
  dataset_images_augmented_path: data/CK_Augmented/CK+_augmented

normalization:
  fer_2013_path: data/FER_2013
  normalization_path: data/normalization

training:
  emotion_csv_file: data/normalization/emotions.csv
  metrics_path: metrics
  model_path: model
  num_labels: 7
  batch_size: 64
  epochs: 30
  train_percentage: 0.8
  show_summary: false